### ISSUE TITLE
After AWS creds have refreshed, Rasterio cannot read from bucket.

### ISSUE THREAD

**Issue by michaelconnor00** [sparkgeo/prescient-sdk#22]
Here is the traceback:

```
CPLE_AWSError                             Traceback (most recent call last)
File rasterio\\_base.pyx:310, in rasterio._base.DatasetBase.__init__()

File rasterio\\_base.pyx:221, in rasterio._base.open_dataset()

File rasterio\\_err.pyx:359, in rasterio._err.exc_wrap_pointer()

CPLE_AWSError: The provided token has expired.

During handling of the above exception, another exception occurred:

RasterioIOError                           Traceback (most recent call last)
Cell In[8], [line 74](vscode-notebook-cell:?execution_count=8&line=74)
     [62](vscode-notebook-cell:?execution_count=8&line=62) raster_file_url = value.href
     [63](vscode-notebook-cell:?execution_count=8&line=63) # https://gdal.org/en/latest/user/configoptions.html
     [64](vscode-notebook-cell:?execution_count=8&line=64) with (
     [65](vscode-notebook-cell:?execution_count=8&line=65)     rasterio.Env(
     [66](vscode-notebook-cell:?execution_count=8&line=66)         GDAL_PAM_ENABLED=False,
     [67](vscode-notebook-cell:?execution_count=8&line=67)         GTIFF_REPORT_COMPD_CS=True,
     [68](vscode-notebook-cell:?execution_count=8&line=68)         GDAL_DISABLE_READDIR_ON_OPEN="EMPTY_DIR",
     [69](vscode-notebook-cell:?execution_count=8&line=69)         GDAL_HTTP_MAX_RETRY=3,
     [70](vscode-notebook-cell:?execution_count=8&line=70)         GDAL_HTTP_RETRY_DELAY=10,
     [71](vscode-notebook-cell:?execution_count=8&line=71)         GDAL_HTTP_RETRY_CODES="ALL",
     [72](vscode-notebook-cell:?execution_count=8&line=72)         session=rasterio_session,
...
    [359](c:\Users\hestvikp\.conda\envs\ENexus\Lib\site-packages\rasterio\__init__.py:359)     )

File rasterio\\_base.pyx:312, in rasterio._base.DatasetBase.__init__()

RasterioIOError: The provided token has expired.
```

In an attempt to rule out an issue with AWS credentials, I increased the temporary creds duration to 4 hours. We are still getting an error: `Error message: Read failed. See previous exception for details`.

At this point I am assuming that Rasterio is holding a cache somewhere. I have confirmed that the credentials do get refreshed as expected. 

There is also the fact that customers notebook could have a programming issue that is causing an old object to be used, but I can't see it. The notebook won't be shared in this issue for security purposes. 

This issue is to create a test script that reads from Rasterio, then waits until creds refresh, then tries to read from Rasterio again. 

Also note, the notebook in question is running this against a dataset in our custonmers environment, which we cannot access. So once the staging env is updated to match, we will be able to run his notebook.

**Comment by underchemist** [comment]
I'm not able to replicate this based on my understanding of the problem. Here is a basic reproducer:

```python
import logging
import sys

import rasterio
from rasterio.session import AWSSession

from prescient_sdk.client import PrescientClient

def worker(session, url):
    with rasterio.Env(session=session, CPL_DEBUG=True, CPL_CURL_VERBOSE=True):
        with rasterio.open(url) as src:
            print(src.checksum(1))

url = "s3://enexus.server-uat.prescient.earth/output/2022_LP_Line_21/UTM_11N_665_6685/assets/UTM_11N_665_6685_22157_INT.tif"

# Set up logging
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

client = PrescientClient()
print(client.bucket_credentials)
rasterio_session = AWSSession(client.session)
worker(rasterio_session, url)

# Refresh credentials
client._auth_credentials.pop("expiration")
print(client.bucket_credentials)

rasterio_session = AWSSession(client.session)
worker(rasterio_session, url)

```
warning: very verbose log of above python script
[prescient_sdk_22.log](https://github.com/user-attachments/files/17467535/prescient_sdk_22.log)

## Notes
From reading through the logs, I believe it confirms that the subsequent rasterio env is using the refreshed session.

**Comment by underchemist** [comment]
referencing the ipynb from client: prescient-sdk-test/1020_philip/raster_stats_stac_enexus_r4.ipynb

I noticed that there are two for loops
1) iterating over vector geometries 
2) iterating over stac items and item assets returned from search query intersecting vector geometry

the credentials are checked, and refreshed if necessary, in the outer for loop. Not knowing anything about the vector data it's possible the inner for loop takes enough time for the existing bucket credentials to expire before being refreshed by re-entering the outer for loop.

**Comment by underchemist** [comment]
additional logs for modified script that sleeps until bucket credentials expire: `python prescient_sdk_22.py > prescient_sdk_22_sleep.log`


```python
import logging
import sys
import datetime
import time

import rasterio
from rasterio.session import AWSSession

from prescient_sdk.client import PrescientClient

def worker(session, url):
    with rasterio.Env(session=session, CPL_DEBUG=True, CPL_CURL_VERBOSE=True):
        with rasterio.open(url) as src:
            print(src.checksum(1))

url = "s3://enexus.server-uat.prescient.earth/output/2022_LP_Line_21/UTM_11N_665_6685/assets/UTM_11N_665_6685_22157_INT.tif"

# Set up logging
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

client = PrescientClient()
print(client.bucket_credentials)
rasterio_session = AWSSession(client.session)
worker(rasterio_session, url)

# Refresh credentials
# client._auth_credentials.pop("expiration")
time_to_sleep = client.bucket_credentials["Expiration"].timestamp() - datetime.datetime.now(datetime.timezone.utc).timestamp()
print("sleeping for: ", time_to_sleep)
time.sleep(time_to_sleep + 1)
print(client.bucket_credentials)

rasterio_session = AWSSession(client.session)
worker(rasterio_session, url)
```
[prescient_sdk_22_sleep.log](https://github.com/user-attachments/files/17478497/prescient_sdk_22_sleep.log)

**Comment by michaelconnor00** [comment]
> the credentials are checked, and refreshed if necessary, in the outer for loop. Not knowing anything about the vector data it's possible the inner for loop takes enough time for the existing bucket credentials to expire before being refreshed by re-entering the outer for loop.

I see your point. Do you think adding progress output with timestamps could make this clear, or maybe he should move the creds refresh function to inside the inner loop. I don't want to get into a code review of his notebook without Natalia giving the ok. 

Based on Philips last email (I will forward to you), after I increased the session duration to 3 hours, he was still getting the error after 1hr...

**Comment by michaelconnor00** [comment]
I just realized that even though I increased the session duration for the role we are assuming, boto3 is asking for creds that expire in 1hr as that is the default set in the SDK. I can see that in your latest log output when it was sleeping for `3596 seconds`.

**Comment by underchemist** [comment]
> I am thinking that we should send this script to Philip to see that it is working as expected. Except it would be good to add some assert checks to show that both the auth and bucket creds values are changing.

👍 

> Based on Philips last email (I will forward to you), after I increased the session duration to 3 hours, he was still getting the error after 1hr...

If I understand correctly, the ipynb does the following:

1) check `client.credentials_expired` (which returns the state of auth credential expiry, not aws)
2) if `True`, refresh both auth and aws credentials and create new boto3 session. Regardless of boto3 default credential duration, or what we set for the role, since we request new aws credentials the session should be new and using different aws credentials.

from what I see in Philip's email is that the aws credentials **do not** change, although the auth credentials do (different bearer token). All that being said I'm already delving too much into this ipynb, I will clean up this dummy test case and we can pass it on to him.

**Comment by michaelconnor00** [comment]
> from what I see in Philip's email is that the aws credentials **do not** change, although the auth credentials do (different bearer token). All that being said I'm already delving too much into this ipynb, I will clean up this dummy test case and we can pass it on to him.

The part I don't get, the AWS creds he shared in his email DO NOT change, yet all of our tests show that once the auth creds expire both auth and bucket creds are refresh and change. Is that not true? Is this just coming down to timing? Maybe we should be setting the bucket session duration to 90 min, and refresh after 60min, which gives a 30 min window to get out of the inner loop. 

However, that is just a bandaid and won't work for other use cases. Can you think of a programmatic way to handle this? Maybe using `yield` and `try/except` blocks to handle pystac_client and rasterio exceptions?

**Comment by underchemist** [comment]
Since we don't have logs from the ipynb, and it's possible the code has changed from the snapshot we have, I'm leaning towards user error in the print statements and/or passing of session objects to rasterio. 

```python
import json
import logging
import sys

import rasterio
from rasterio.session import AWSSession

from prescient_sdk.client import PrescientClient


def worker(session, url):
    with rasterio.Env(session=session, CPL_DEBUG=True, CPL_CURL_VERBOSE=True):
        with rasterio.open(url) as src:
            return src.checksum(1)


url = "s3://enexus.server-uat.prescient.earth/output/2022_LP_Line_21/UTM_11N_665_6685/assets/UTM_11N_665_6685_22157_INT.tif"

# Set up logging
logging.basicConfig(
    format="%(asctime)s %(levelname)s %(name)-8s %(message)s",
    stream=sys.stdout,
    level=logging.DEBUG,
)

client = PrescientClient()
results = []
session = AWSSession(client.session)
results.append(
    {
        "checksum": worker(session, url),
        "bucket_credentials": client.bucket_credentials,
        "session": session,
    }
)

# Refresh credentials
client._auth_credentials.pop("expiration")

session = AWSSession(client.session)
results.append(
    {
        "checksum": worker(client.session, url),
        "bucket_credentials": client.bucket_credentials,
        "session": session,
    }
)

for i, result in enumerate(results):
    print("iteration: ", i)
    print(
        "bucket_credentials:\n",
        json.dumps(result["bucket_credentials"], indent=2, default=str),
        "\n",
    )
    print(
        "session credentials:\n",
        json.dumps(result["session"].credentials, indent=2),
        "\n",
    )
    print("checksum:", result["checksum"], "\n")


assert results[0]["checksum"] == results[1]["checksum"]
assert not any(
    results[0]["bucket_credentials"][key] == results[1]["bucket_credentials"][key]
    for key in results[0]["bucket_credentials"]
)
assert not any(
    results[0]["session"].credentials[key] == results[1]["session"].credentials[key]
    for key in results[0]["session"].credentials
)
```

updated test case with timestamps and asserts. If Philip can run this and report back the logs to us that would be a good next step.

**Comment by michaelconnor00** [comment]
Thanks! I will email this to him.

**Comment by michaelconnor00** [comment]
What do you think about adding a `force_refresh=True` parameter so we explicitly getting new credentials. For example: `client.bucket_credentials(force_refresh=True)`. This would allow the user to ensure they are getting new credentials. Another option would be to create an invalidate function.

**Comment by underchemist** [comment]
I think that's valid, though in your former example since it's a decorated `@property` method it's not callable and arguments can't be passed to it. So probably the latter, a method to force clear the credential(s)

**Comment by michaelconnor00** [comment]
I prefer the `force_refresh` method. It means changing them from properties to functions, which would be a breaking change.
