### ISSUE TITLE
Make the client more generic in terms of auth providers

### ISSUE THREAD

**Issue by gnieuwenhuis** [sparkgeo/prescient-sdk#5]
Currently the client is set up specifically for auth through Azure AD. We want to make it easy to add support for different auth providers.

To enable this for future clients, change the property name `azure_credentials` on the client to something more generic - maybe `get_credentials`.

Also need to change the config variable names so that nothing named `azure` remains, and it is entirely generic.

**Comment by michaelconnor00** [comment]
I also think we should only have one name for each variable. For example, currently `ENDPOINT_URL` is acceptable in the `config.env` but must be `PRESCIENT_ENDPOINT_URL` in env vars. I think these should be the same name to avoid confusion.
